###
# Project-specific config file
#
# Note that this will be included *after* config/*.yml

title: "Zonas Horarias en Python"
subtitle: "Todo lo que ojalá no necesitases"
talk_github_url: "pganssle-talks/2026-pycon-us-zonas-horarias"
plugins_dir: [_plugins, _local_plugins]
